/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x80u    /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_I2CDRIVE_LOW 0x00u  /*!<@brief Low drive: 4 mA */
#define IOCON_PIO_I2CFILTER_EN 0x00u  /*!<@brief I2C 50 ns glitch filter enabled */
#define IOCON_PIO_I2CSLEW_GPIO 0x20u  /*!<@brief GPIO mode */
#define IOCON_PIO_INPFILT_OFF 0x0100u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x10u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */
#define PIO112_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO112_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO114_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO114_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO115_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO115_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO11_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO11_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */

/*! @name FC0_RXD_SDA_MOSI (number 31), U18[4]/TO_MUX_P0_0-ISP_RX
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO (number 32), U6[4]/U22[3]/P0_1-ISP_TX
  @{ */
/* @} */

/*! @name PIO0_29 (number 11), J2[5]/D2[1]/P0_29-CT32B0_MAT3-RED
  @{ */
#define BOARD_INITPINS_LED_RED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED_RED_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_LED_RED_PIN 29U   /*!<@brief 0U pin index: 29 */
                                         /* @} */

/*! @name PIO1_10 (number 30), J9[8]/D2[4]/P1_10-SCT4-LED_GREEN
  @{ */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED_GREEN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_LED_GREEN_PIN 10U   /*!<@brief 1U pin index: 10 */
                                           /* @} */

/*! @name PIO1_9 (number 29), J9[5]/D2[3]/P1_9-BLUE_LED
  @{ */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED_BLUE_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_LED_BLUE_PIN 9U    /*!<@brief 1U pin index: 9 */
                                          /* @} */

/*! @name PIO1_1 (number 15), J1[15]/P1_1-FC5_SSEL2
  @{ */
#define BOARD_INITPINS_SWITCH1_SPEED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_SWITCH1_SPEED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_SWITCH1_SPEED_PIN 1U    /*!<@brief 1U pin index: 1 */
                                               /* @} */

/*! @name PIO1_15 (number 62), J1[17]/P1_15-SCTO5-FC7_CTS
  @{ */
#define BOARD_INITPINS_SWITCH1_DIRECTION_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_SWITCH1_DIRECTION_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_SWITCH1_DIRECTION_PIN 15U   /*!<@brief 1U pin index: 15 */
                                                   /* @} */

/*! @name PIO1_14 (number 57), J2[1]/P1_14-SCTO7
  @{ */
#define BOARD_INITPINS_SWITCH2_SPEED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_SWITCH2_SPEED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_SWITCH2_SPEED_PIN 14U   /*!<@brief 1U pin index: 14 */
                                               /* @} */

/*! @name PIO1_12 (number 51), J2[9]/P1_12-CT32B1_MAT0-ACCl_INT1
  @{ */
#define BOARD_INITPINS_SWITCH2_DIRECTION_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_SWITCH2_DIRECTION_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_SWITCH2_DIRECTION_PIN 12U   /*!<@brief 1U pin index: 12 */
                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
